server.port=8082
spring.application.name=driver-vehicle-service

# MongoDB Database Configuration 
spring.data.mongodb.uri=mongodb+srv://it24102440_db_user:venu@cluster0.csujsn5.mongodb.net/driverdb?retryWrites=true&w=majority

# Actuator Endpoints (For monitoring)
management.endpoints.web.exposure.include=*